# Generated by Django 4.2.15 on 2025-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.CharField(max_length=50)),
                ('vcpu', models.CharField(max_length=50)),
                ('vram', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('pbs', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=50)),
                ('dmz', models.CharField(max_length=50)),
            ],
        ),
    ]
