# Generated by Django 4.2.15 on 2025-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_adm_hours_record_disk_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_accepted',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
