# Generated by Django 4.2.15 on 2025-03-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_record_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
