# Generated by Django 4.2.15 on 2025-03-12 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='adm_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='disk',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20, 'Minimalna wartość to 20'), django.core.validators.MaxValueValidator(1000, 'Maksymalna wartość to 1000')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='disk_profile',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimalna wartość to 1'), django.core.validators.MaxValueValidator(3, 'Maksymalna wartość to 3')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='is_accepted',
            field=models.CharField(blank=True, default='No', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='pbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='pbs_replication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rds_cal_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rds_cal_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='rds_cal_perpetual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='vcpu',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimalna wartość to 1'), django.core.validators.MaxValueValidator(32, 'Maksymalna wartość to 32')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='vram',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimalna wartość to 1'), django.core.validators.MaxValueValidator(32, 'Maksymalna wartość to 32')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='ws2022_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ws2022_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ws2022_cal_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='ws2022_cal_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
