# Generated by Django 4.2.15 on 2025-03-12 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_record_adm_hours_alter_record_disk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pub_net_speed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimalna wartość to 100'), django.core.validators.MaxValueValidator(3, 'Maksymalna wartość to 1000')]),
        ),
    ]
