# Generated by Django 4.2.15 on 2025-03-12 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_record_pub_net_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='disk_profile',
            field=models.IntegerField(blank=True, default='1', null=True, validators=[django.core.validators.MinValueValidator(1, 'Minimalna wartość to 1'), django.core.validators.MaxValueValidator(3, 'Maksymalna wartość to 3')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='ip',
            field=models.IntegerField(blank=True, default='0', null=True, validators=[django.core.validators.MinValueValidator(0, 'Minimalna wartość to 0'), django.core.validators.MaxValueValidator(20, 'Maksymalna wartość to 20')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='pub_net_speed',
            field=models.IntegerField(blank=True, default='100', null=True, validators=[django.core.validators.MinValueValidator(100, 'Minimalna wartość to 100'), django.core.validators.MaxValueValidator(1000, 'Maksymalna wartość to 1000')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, default='In progress', max_length=50, null=True),
        ),
    ]
