# Generated by Django 4.2.15 on 2025-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_record_disk_profile_alter_record_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='procedure',
            field=models.CharField(blank=True, default='Nowa maszyna', max_length=50, null=True),
        ),
    ]
