# Generated by Django 4.2.15 on 2025-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_record_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ids_ips',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
